version: '2'
services:
    ### PHP-FPM ###
    php7:
        build: php7
        volumes:
            - ./www/:/var/www/html/:rw
        ports:
            - "9009:9000"
        restart: always

    ### Nginx
    nginx:
        image: nginx:alpine
        volumes:
            - ./www/:/var/www/html/:rw
            - ./nginx/conf.d:/etc/nginx/conf.d/:ro
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/log/:/var/log/nginx/:rw
        ports:
            - "81:80"
            - "444:443"
        links:
            - php7

    ### Mysql
    mysql:
        build: mysql
        volumes:
            - ./data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: WHlyd666
            MYSQL_USER: lustre
            MYSQL_PASSWORD: 64648412qwE
        ports:
            - "3307:3306"
   
    ### Redis
    redis:
        build: redis
        volumes: 
             - ./data/cache:/data
        ports:
            - "6380:6379"
